[workspace]
members = [
    "bevy-lua-ecs",
    "Hello"
]
resolver = "2"

[workspace.dependencies]
bevy = "0.16"
mlua = { version = "0.10", features = ["lua54", "send", "vendored", "serialize"] }
serde = "1.0"
serde_json = "1.0"
bevy_rapier2d = { version = "0.31", features = ["serde-serialize"] }
